### ISSUE TITLE
IONIC stream camera

### ISSUE THREAD

**Issue by DanielnetoDotCom** [disono/cordova-rtmp-rtsp-stream#1]
Hi, can you give me some help/example how to publish the camera on IONIC?

**Comment by disono** [comment]
Ionic version?

I assume you are using latest version of Ionic(v2+).
Make also sure the permission ask by the plugin is allowed.

```
// your imports here

declare let videoStreamer;

class name {
methodName() {
videoStreamer.streamRTSPAuth('rtsp://your-ip/live/app_name', 'your-username', 'your-password', [success], [failed]);
}
}
```

**Comment by DanielnetoDotCom** [comment]
@disono 
Thanks I could make it work. thanks
There is a way to improve video quality/resolution?

**Comment by qiangci** [comment]
Hello,may i help me?
I used it this way,but it reminded me that videoStreamer is not defined,Didn't I introduce anything?
Could you tell me how to do it?

**Comment by krishna022** [comment]
Hi,
I am trying to install the "cordova-rtmp-rtsp-stream" in ionic 3.
But I did't find any document related to ionic app. 
I have installed the plugin but have no idea that what to import in the "app.module.ts"
import { videoStreamer } from 'cordova-rtsp-rtmp-stream';
And how to create the *import and constructor* in the .ts file of the page.

Kindly Assist me.

**Comment by braindotai** [comment]
@krishna022 have you found any solution for it yet? I'm also troubling regarding the same, there are docs like how to use cordova plugins but not able to find any info at all about importing a cordova plugin in the ionic angular component ts file.
