### ISSUE TITLE
[Request] Portrait screen and screen size

### ISSUE THREAD

**Issue by litiobat** [disono/cordova-rtmp-rtsp-stream#10]
Hi!
I've got 2 request about your plugin:
- It's possible to use in PORTRAIT mode? (now force landscape)
- It's to possible set the height of the Layout, showing the background (Cordova HTML page) in the rest of screen (for example 50%-50%)?

Thank you very much!

**Comment by nyeineagle** [comment]
I'm having this problem now,plz answer..
