### ISSUE TITLE
where and how to import videoStreamer?

### ISSUE THREAD

**Issue by braindotai** [disono/cordova-rtmp-rtsp-stream#21]
Im unable to use this awesome library, would anyone help me figuring out how to import this library in a angular ionic project?
I've tried this:
```js
import * as videoStreamer from 'cordova-rtsp-rtmp-stream';
```
and this:
```js
import { videoStreamer } from 'cordova-rtsp-rtmp-stream';
```
but nothing worked

Thanks for your time.

**Comment by disono** [comment]
You can use this more updated plugin based on capacitor
https://github.com/disono/capacitor-rtsp-rtmp-stream
