### ISSUE TITLE
IOs Support

### ISSUE THREAD

**Issue by DanielnetoDotCom** [disono/cordova-rtmp-rtsp-stream#4]
Is possible to make it work for IOS?

**Comment by DanielnetoDotCom** [comment]
Are you thinking to implement this: https://github.com/LaiFengiOS/LFLiveKit?

**Comment by disono** [comment]
currently I'm already working on it...

**Comment by DanielnetoDotCom** [comment]
There is a way I can support you or fund you with that?

**Comment by ingageco** [comment]
@disono Same - i'll support financially to fast track this. Let us know! Thanks.

**Comment by bijanmmarkes** [comment]
Any news on this?
