### ISSUE TITLE
Comment List and another options

### ISSUE THREAD

**Issue by alaanasreng** [disono/cordova-rtmp-rtsp-stream#9]
Hello Sir,

Firstly, Thanks for great work.
Secondly,
- What is the structure of comments list parameter passed to commentList?
- Can i update comments by showing new comments added?
- How to hide some button on live stream view e.g. REC, Flash button?
- Can i make stream started automatically, without click on camera icon on live stream view?

also i found that camera is stretched, is there any option can i make to solve this problem?

Best Regards

**Comment by disono** [comment]
I updated the README.md for the comment options.
I will update the plugin for the other options (Hiding option for REC, Flash etc, Auto streaming)
